name: Issues

on:
  issues:
    types: [opened]
env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
  
jobs:
  print_issue_title:
    runs-on: ubuntu-latest

    name: Print issue title sf
    steps:
    - run: echo "${{github.event.issue.title}}"
